### ISSUE TITLE
ERROR: Failed building wheel for flightgym

### ISSUE THREAD

**Issue by davitdavtyan** [uzh-rpg/flightmare#166]
Hi dear correspondent  
After pip install . I am having following log of errors.

 Building wheel for flightgym (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/sellis/anaconda3/envs/ENVNAME_py36/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/sellis/Desktop/flightmare/flightlib/setup.py'"'"'; __file__='"'"'/home/sellis/Desktop/flightmare/flightlib/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5bovee5y
       cwd: /home/sellis/Desktop/flightmare/flightlib/
  Complete output (39 lines):
  running bdist_wheel
  running build
  running build_ext
  CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "/home/sellis/Desktop/flightmare/flightlib/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/sellis/Desktop/flightmare/flightlib/setup.py", line 106, in <module>
      zip_safe=False,
    File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/sellis/Desktop/flightmare/flightlib/setup.py", line 59, in run
      self.build_extension(ext)
    File "/home/sellis/Desktop/flightmare/flightlib/setup.py", line 89, in build_extension
      cmake_args, cwd=self.build_temp, env=env)
    File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/home/sellis/Desktop/flightmare/flightlib', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/sellis/Desktop/flightmare/flightlib/build/lib.linux-x86_64-3.6/', '-DPYTHON_EXECUTABLE=/home/sellis/anaconda3/envs/ENVNAME_py36/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for flightgym
  Running setup.py clean for flightgym
Failed to build flightgym
Installing collected packages: flightgym
  Attempting uninstall: flightgym
    Found existing installation: flightgym 0.0.1
    Uninstalling flightgym-0.0.1:
      Successfully uninstalled flightgym-0.0.1
    Running setup.py install for flightgym ... error
    ERROR: Command errored out with exit status 1:
     command: /home/sellis/anaconda3/envs/ENVNAME_py36/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/sellis/Desktop/flightmare/flightlib/setup.py'"'"'; __file__='"'"'/home/sellis/Desktop/flightmare/flightlib/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cjw4icmj/install-record.txt --single-version-externally-managed --compile --install-headers /home/sellis/anaconda3/envs/ENVNAME_py36/include/python3.6m/flightgym
         cwd: /home/sellis/Desktop/flightmare/flightlib/
    Complete output (41 lines):
    running install
    running build
    running build_ext
    CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "/home/sellis/Desktop/flightmare/flightlib/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/sellis/Desktop/flightmare/flightlib/setup.py", line 106, in <module>
        zip_safe=False,
      File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/sellis/Desktop/flightmare/flightlib/setup.py", line 59, in run
        self.build_extension(ext)
      File "/home/sellis/Desktop/flightmare/flightlib/setup.py", line 89, in build_extension
        cmake_args, cwd=self.build_temp, env=env)
      File "/home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/home/sellis/Desktop/flightmare/flightlib', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/sellis/Desktop/flightmare/flightlib/build/lib.linux-x86_64-3.6/', '-DPYTHON_EXECUTABLE=/home/sellis/anaconda3/envs/ENVNAME_py36/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
  Rolling back uninstall of flightgym
  Moving to /home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/site-packages/flightgym-0.0.1.dist-info/
   from /home/sellis/anaconda3/envs/ENVNAME_py36/lib/python3.6/site-packages/~lightgym-0.0.1.dist-info
ERROR: Command errored out with exit status 1: /home/sellis/anaconda3/envs/ENVNAME_py36/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/sellis/Desktop/flightmare/flightlib/setup.py'"'"'; __file__='"'"'/home/sellis/Desktop/flightmare/flightlib/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cjw4icmj/install-record.txt --single-version-externally-managed --compile --install-headers /home/sellis/anaconda3/envs/ENVNAME_py36/include/python3.6m/flightgym Check the logs for full command output.

Is there anything I have to perform ahead, please?

Thank you in advance

**Comment by davitdavtyan** [comment]
This have been resolved by [https://github.com/uzh-rpg/flightmare/issues/151#issuecomment-1010913441](url), so thanks to [https://github.com/LIU-Xueming](url), but then I had another issue related to CXX of cmake. So I were had to do "sudo apt-get update && sudo apt-get install build-essential". And rerunning "pip install -e", was showing proper compilation,  which led to another issue: 

In file included from /home/sellis/Desktop/flightmare/flightlib/src/bridges/unity_bridge.cpp:1:
    /home/sellis/Desktop/flightmare/flightlib/include/flightlib/bridges/unity_bridge.hpp:19:10: fatal error: zmqpp/zmqpp.hpp: No such file or directory
       19 | #include <zmqpp/zmqpp.hpp>
          |          ^~~~~~~~~~~~~~~~~
    compilation terminated.

that i am fighting now with.

**Comment by davitdavtyan** [comment]
The zmqpp/zmqpp.hpp installation solved the problem and I got flightmare installed successfully. Though I were had to do  zmqpp libraries installation manually.
