### ISSUE TITLE
Issue with installing flightmare

### ISSUE THREAD

**Issue by spnd-vig** [uzh-rpg/flightmare#182]
**I am getting this error while entering into flightlib directory and issuing pip install . command:

(This is last few lines of the output)**

File "/tmp/pip-install-p36rsui7/atari-py_73d120c27bd94c5caa27670917c355d6/setup.py", line 21, in run
          subprocess.check_call(['cmake', '--build', '.'], cwd=cwd)
        File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> atari-py

note: This is an issue with the package mentioned above, not pip.

**Comment by spnd-vig** [comment]
I resolved that error by installing python310-devel. The issue was that gcc wasnt able to locate Python.h.

But now i am stuck here:



Running setup.py install for flightgym ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for flightgym did not run successfully.
  │ exit code: 1
  ╰─> [108 lines of output]
      running install
      /home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      Removing some cache file:  /home/spanda/Desktop/flightmare/flightlib/externals/eigen
      Removing some cache file:  /home/spanda/Desktop/flightmare/flightlib/externals/pybind11-download
      Removing some cache file:  /home/spanda/Desktop/flightmare/flightlib/externals/pybind11-bin
      Removing some cache file:  /home/spanda/Desktop/flightmare/flightlib/externals/pybind11-src
      Removing some cache file:  /home/spanda/Desktop/flightmare/flightlib/externals/yaml-download
      Removing some cache file:  /home/spanda/Desktop/flightmare/flightlib/externals/yaml-bin
      Removing some cache file:  /home/spanda/Desktop/flightmare/flightlib/externals/yaml-src
      Removing some cache file:  /home/spanda/Desktop/flightmare/flightlib/externals/yaml-build
      -- The C compiler identification is GNU 7.5.0
      -- The CXX compiler identification is GNU 7.5.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- ======================  !Flightmare!  ======================
      -- ======> Setup Dependencies
      -- No sufficient Eigen version (3.3.4) found.
      -- Restoring to download Eigen sources.
      -- Getting Eigen...
      Cloning into 'eigen3'...
      HEAD is now at 3dc3a0ea2 bump to 3.3.4
      -- Eigen downloaded!
      -- Eigen3 include dir:
      -- Getting Pybind11...
      Cloning into 'pybind11-src'...
      Already on 'master'
      -- Pybind11 downloaded!
      -- pybind11 v2.11.0 dev1
      -- Found PythonInterp: /home/spanda/flightmare/bin/python3.10 (found suitable version "3.10.8", minimum required is "3.6")
      -- Found PythonLibs: /usr/lib64/libpython3.10.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Getting yaml-cpp...
      -- Yaml downloaded!
      CMake Error at CMakeLists.txt:50 (find_package):
        By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "OpenCV", but
        CMake did not find one.
      
        Could not find a package configuration file provided by "OpenCV" with any
        of the following names:
      
          OpenCVConfig.cmake
          opencv-config.cmake
      
        Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
        "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
        provides a separate development package or SDK, be sure it has been
        installed.
      
      
      -- Configuring incomplete, errors occurred!
      See also "/home/spanda/Desktop/flightmare/flightlib/build/temp.linux-x86_64-cpython-310/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/spanda/Desktop/flightmare/flightlib/setup.py", line 94, in <module>
          setup(
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/_distutils/command/install.py", line 695, in run
          self.run_command('build')
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/spanda/flightmare/lib64/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/spanda/Desktop/flightmare/flightlib/setup.py", line 59, in run
          self.build_extension(ext)
        File "/home/spanda/Desktop/flightmare/flightlib/setup.py", line 88, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] +
        File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/home/spanda/Desktop/flightmare/flightlib', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/spanda/Desktop/flightmare/flightlib/build/lib.linux-x86_64-cpython-310/', '-DPYTHON_EXECUTABLE=/home/spanda/flightmare/bin/python3.10', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> flightgym

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by lkbarth** [comment]
Have you installed the recommended packages as mentioned in the following link (https://github.com/uzh-rpg/flightmare/wiki/Install-with-pip)?

**Comment by AnshShah3009** [comment]
any updates? @spnd-vig
