### ISSUE TITLE
 subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

### ISSUE THREAD

**Issue by guytenn** [uzh-rpg/flightmare#55]
I'm getting this error when calling pip install . in the flightlib directory (after installing all prerequisites). Any ideas?
Full log:

ERROR: Command errored out with exit status 1:
     command: /home/guy/Projects/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/guy/Projects/flightmare/flightlib/setup.py'"'"'; __file__='"'"'/home/guy/Projects/flightmare/flightlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/guy/Projects/flightmare/flightlib/
    Complete output (162 lines):
    running develop
    running egg_info
    writing flightgym.egg-info/PKG-INFO
    writing dependency_links to flightgym.egg-info/dependency_links.txt
    writing requirements to flightgym.egg-info/requires.txt
    writing top-level names to flightgym.egg-info/top_level.txt
    reading manifest file 'flightgym.egg-info/SOURCES.txt'
    writing manifest file 'flightgym.egg-info/SOURCES.txt'
    running build_ext
    -- The C compiler identification is GNU 9.3.0
    -- The CXX compiler identification is GNU 9.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- ======================  !Flightmare!  ======================
    -- ======> Setup Dependencies
    -- No sufficient Eigen version (3.3.4) found.
    -- Restoring to download Eigen sources.
    -- Getting Eigen...
    Cloning into 'eigen3'...
    Already on 'master'
    -- Eigen downloaded!
    -- Eigen3 include dir:
    -- Getting Pybind11...
    Cloning into 'pybind11-src'...
    Already on 'master'
    -- Pybind11 downloaded!
    -- pybind11 v2.6.1 dev1
    -- Found PythonInterp: /home/guy/Projects/venv/bin/python3 (found version "3.8.2")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- Getting yaml-cpp...
    -- Yaml downloaded!
    -- Found OpenCV: /usr (found version "4.2.0")
    -- Found OpenMP_C: -fopenmp (found version "4.5")
    -- Found OpenMP_CXX: -fopenmp (found version "4.5")
    -- Found OpenMP: TRUE (found version "4.5")
    INFOBuild time could be improved with ccache!
    INFO    sudo apt install ccache
    -- ======> Setup Compilation
    -- Enabling fast optimization flags!
    -- The activated CXX RELEASE configuration is:
     -DVERSION_INFO=\"0.0.1\" -fPIC -Wall -DNDEBUG  -fopenmp  -Ofast  -march=native
    -- The activated CXX DEBUG configuration is:
     -DVERSION_INFO=\"0.0.1\" -fPIC -Wall -g -fopenmp
    -- ======>  Setup Build
    -- Getting gtests...
    Cloning into 'googletest-src'...
    Already on 'master'
    -- gtests downloaded!
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- ================  !Done. No more nightmare!  ================
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/guy/Projects/flightmare/flightlib/build/temp.linux-x86_64-3.8
    Scanning dependencies of target gtest
    Scanning dependencies of target yaml-cpp
    [  1%] Building CXX object ../../externals/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
    [  2%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilderadapter.cpp.o
    [  5%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o
    [  5%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/binary.cpp.o
    [  6%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/convert.cpp.o
    [  8%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/depthguard.cpp.o
    [  9%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/directives.cpp.o
    [ 10%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/emit.cpp.o
    [ 12%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/emitfromevents.cpp.o
    [ 13%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/emitter.cpp.o
    [ 14%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/emitterstate.cpp.o
    [ 16%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/emitterutils.cpp.o
    [ 17%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/exceptions.cpp.o
    [ 18%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/exp.cpp.o
    [ 20%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/memory.cpp.o
    [ 21%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/node.cpp.o
    [ 22%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/node_data.cpp.o
    [ 24%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/nodebuilder.cpp.o
    [ 25%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/nodeevents.cpp.o
    [ 27%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/null.cpp.o
    [ 28%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/ostream_wrapper.cpp.o
    [ 29%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/parse.cpp.o
    [ 31%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/parser.cpp.o
    [ 32%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/regex_yaml.cpp.o
    [ 33%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/scanner.cpp.o
    [ 35%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/scanscalar.cpp.o
    [ 36%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/scantag.cpp.o
    [ 37%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/scantoken.cpp.o
    [ 39%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/simplekey.cpp.o
    [ 40%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/singledocparser.cpp.o
    [ 41%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/stream.cpp.o
    [ 43%] Building CXX object ../../externals/yaml-build/CMakeFiles/yaml-cpp.dir/src/tag.cpp.o
    [ 44%] Linking CXX static library libyaml-cpp.a
    [ 44%] Built target yaml-cpp
    Scanning dependencies of target flightlib
    [ 45%] Building CXX object CMakeFiles/flightlib.dir/src/common/command.cpp.o
    [ 47%] Building CXX object CMakeFiles/flightlib.dir/src/common/integrator_base.cpp.o
    [ 48%] Building CXX object CMakeFiles/flightlib.dir/src/bridges/unity_bridge.cpp.o
    [ 50%] Linking CXX static library ../../../build/temp.linux-x86_64-3.8/lib/libgtest.a
    [ 50%] Built target gtest
    [ 51%] Building CXX object CMakeFiles/flightlib.dir/src/common/integrator_euler.cpp.o
    [ 52%] Building CXX object CMakeFiles/flightlib.dir/src/common/integrator_rk4.cpp.o
    [ 54%] Building CXX object CMakeFiles/flightlib.dir/src/common/logger.cpp.o
    [ 55%] Building CXX object CMakeFiles/flightlib.dir/src/common/math.cpp.o
    [ 56%] Building CXX object CMakeFiles/flightlib.dir/src/common/parameter_base.cpp.o
    /home/guy/Projects/flightmare/flightlib/src/bridges/unity_bridge.cpp: In member function ‘bool flightlib::UnityBridge::handleOutput()’:
    /home/guy/Projects/flightmare/flightlib/src/bridges/unity_bridge.cpp:237:46: error: ‘CV_RGB2BGR’ was not declared in this scope; did you mean ‘CV_RGB’?
      237 |           cv::cvtColor(new_image, new_image, CV_RGB2BGR);
          |                                              ^~~~~~~~~~
          |                                              CV_RGB
    [ 58%] Building CXX object CMakeFiles/flightlib.dir/src/common/pend_state.cpp.o
    [ 59%] Building CXX object CMakeFiles/flightlib.dir/src/common/quad_state.cpp.o
    make[2]: *** [CMakeFiles/flightlib.dir/build.make:63: CMakeFiles/flightlib.dir/src/bridges/unity_bridge.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    Scanning dependencies of target gtest_main
    [ 60%] Building CXX object ../../externals/googletest-build/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
    [ 62%] Linking CXX static library ../../../build/temp.linux-x86_64-3.8/lib/libgtest_main.a
    [ 62%] Built target gtest_main
    make[1]: *** [CMakeFiles/Makefile2:321: CMakeFiles/flightlib.dir/all] Error 2
    make: *** [Makefile:141: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/guy/Projects/flightmare/flightlib/setup.py", line 94, in <module>
        setup(
      File "/home/guy/Projects/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/guy/Projects/venv/lib/python3.8/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/guy/Projects/venv/lib/python3.8/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/guy/Projects/flightmare/flightlib/setup.py", line 59, in run
        self.build_extension(ext)
      File "/home/guy/Projects/flightmare/flightlib/setup.py", line 90, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] +
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
    ----------------------------------------
  ERROR: Can't roll back flightgym; was not uninstalled
ERROR: Command errored out with exit status 1: /home/guy/Projects/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/guy/Projects/flightmare/flightlib/setup.py'"'"'; __file__='"'"'/home/guy/Projects/flightmare/flightlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output

**Comment by slimeth** [comment]
It's a version problem as we don't use CV 4.2. There has been a solution proposed in [this issue](https://github.com/uzh-rpg/flightmare/issues/23).

**Comment by siddas27** [comment]
Following the below link worked for me.
[https://github.com/uzh-rpg/flightmare/wiki/Install-with-pip](https://github.com/uzh-rpg/flightmare/wiki/Install-with-pip)
