### ISSUE TITLE
ddc_challenge: error running pre-trained model

### ISSUE THREAD

**Issue by jhurlbut** [uzh-rpg/flightmare#98]
When running "python3 run_drone_control.py --train 0" to test the pre-trained model I get an error:

Traceback (most recent call last):
  File "run_drone_control.py", line 116, in <module>
    main()
  File "run_drone_control.py", line 111, in main
    model = PPO.load(args.weight)
  File "/root/miniconda3/envs/RL/lib/python3.6/site-packages/stable_baselines3/common/base_class.py", line 636, in load
    policy=data["policy_class"],
KeyError: 'policy_class'

It looks like maybe the yaml in the quadrotor_env.zip file is malformed?

**Comment by lorenzoferrini** [comment]
Yes, I think the zip file was generated with stable-baselines2 while the version implemented for the challenge is stable-baselines3. 
I would suggest you to just ignore it and replace it with one of your trained models as soon as you have one.
